### ISSUE TITLE
Create "Call for Proposals" Flyer for March 23 Meetup

### ISSUE THREAD

**Issue by inovizz** [HydPy/hydpy-tasks#1]

**Comment by bpkapkar** [comment]
![Hydpy_Call_For_Sprakers](https://user-images.githubusercontent.com/49440262/222953366-47938275-8193-48d6-b7e0-be19f190abe4.png)

Call for Proposals Flyer for March 23 Meetup , Please do check.

**Comment by inovizz** [comment]
Looks good to me.

@kalyan678  - can you post it on all SM channels tomorrow?
