### ISSUE TITLE
Create an event page on meetup for 15th April Workshop

### ISSUE THREAD

**Issue by inovizz** [HydPy/hydpy-tasks#2]

**Comment by bpkapkar** [comment]
Yes , will create it.  Should we wait for poster to get ready, or we can create the place holder and further upload the poster in placeholder @inovizz

**Comment by inovizz** [comment]
placeholder is fine I think.

**Comment by bpkapkar** [comment]
Created draft version of the meetup page , waiting for team to review it , once done it can be publish.
