### ISSUE TITLE
Create a poster/flyer for 15th April meetup (workshop)

### ISSUE THREAD

**Issue by inovizz** [HydPy/hydpy-tasks#3]

**Comment by vijay-teddy** [comment]
We have a design. Need confirmation for location and link. 
![Image](https://user-images.githubusercontent.com/29485213/227760866-4b78019b-8c46-4260-bd13-0f096e79b385.png)

**Comment by vijay-teddy** [comment]
Updated

![Image](https://user-images.githubusercontent.com/29485213/227763928-972e1af0-27fc-4660-ac37-bd2d955caea1.png)

**Comment by vijay-teddy** [comment]
![Image](https://user-images.githubusercontent.com/29485213/227954555-da549953-cb23-433c-a79e-3f2ddcf5d8ef.png)
